services:
  - type: web
    name: consulta-proxy
    env: python
    region: oregon
    buildCommand: pip install -r requirements_render.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port 10000
    plan: free
